# Generated by Django 5.2.3 on 2025-06-26 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('sharh', models.CharField(max_length=300, verbose_name='شرح کالا')),
                ('vahed', models.CharField(max_length=50, verbose_name='واحد')),
                ('meghdar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('shomare_faktor', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره فاکتور')),
                ('fi', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='فی (ریال)')),
                ('takhfif', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تخفیف (درصدی)')),
                ('mablagh', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ کل (ریال)')),
                ('vaziat_mali', models.CharField(choices=[('تسویه', 'تسویه'), ('مانده', 'مانده')], max_length=50, verbose_name='وضعیت مالی')),
                ('taahod', models.CharField(choices=[('علوی', 'علوی'), ('بهزادی', 'بهزادی'), ('رحمانی', 'رحمانی'), ('پرداختی', 'پرداختی')], max_length=100, verbose_name='تعهد')),
                ('anbar', models.CharField(max_length=100, verbose_name='انبار')),
                ('mahale_estefade', models.CharField(blank=True, max_length=200, null=True, verbose_name='محل استفاده')),
                ('tozihat', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('mahale_tamin', models.CharField(blank=True, max_length=200, null=True, verbose_name='محل تامین')),
                ('tasvir_faktor', models.ImageField(blank=True, null=True, upload_to='invoices/', verbose_name='تصویر فاکتور')),
                ('tasvir_resid', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر رسید تحویل')),
            ],
            options={
                'verbose_name': 'سند ورود',
                'verbose_name_plural': 'اسناد ورود',
                'ordering': ['-tarikh', '-id'],
            },
        ),
    ]
